### ISSUE TITLE
Generation of address_mod may end up with 31 byte long values that crash runtime

### ISSUE THREAD

**Issue by aorumbayev** [giuliop/whitelist-example-algoplonk#1]
The line 66 in add_address_to_whitelist contains 
```py
address_mod = Bytes32.from_bytes(
            (py.BigUInt.from_bytes(address.bytes) % curve_mod).bytes
        )
```

Certain addresses (didn't pin point which exact), can result in the address_mode value being 31 byte long, the from_bytes does not verify size contraints hence this compiles however may crash in certain scenarios. 

We use this contract as an example to showcase how testing can be done with supplementary algorand-python-testing package and we spotted this as intermittent bug. See detailed logs here https://github.com/algorandfoundation/algorand-python-testing/actions/runs/9871835845/job/27260611694?pr=2

**Comment by giuliop** [comment]
Indeed the error happens when the Algorand address modulo the curve modulus is less than 32 bytes.

An example of that would be the address `GEVOXRKJ5VODRIAHEYL3SS6PXFGDNFGB7KGUVKOHL532GDHKH43JZQYTXM` which resolves to a 31 byte number modulo the curve modulus.

I thought erroneously that `Bytes32.from_bytes()` would pad.

The fix is to simply modify line 66 adding explicit padding:
```
address_mod = Bytes32.from_bytes(
    py.op.bzero(32) | (py.BigUInt.from_bytes(address.bytes) % curve_mod).bytes
)
```

I will release a fixed contract on TestNet and publish a new tagged commit for the repo.

Thank you for pointing this out!
